import { Injectable } from '@angular/core';
import { Transfer } from './services/transfer';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Injectable({
  providedIn: 'root'
})
export class InvoiceService {

  constructor() { }

  generateTransferPdf(transfer: Transfer): void {
    const date = new Date();
    const dateString = `${date.getHours()}:${date.getMinutes()} ${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()}`;
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.setTextColor(40, 40, 40);
    doc.text('Transfer Report', 105, 20, { align: 'center' });


    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Date: ${dateString}`, 105, 30, { align: 'center' });

    let y = 40;

    doc.setLineWidth(0.5);
    doc.line(10, y, 200, y);
    y += 10;

    const transferDate = new Date(transfer.transferDate);
    const transferDateString = isNaN(transferDate.getTime()) ? 'Invalid date' : `${transferDate.toLocaleDateString()} ${transferDate.toLocaleTimeString()}`;

    doc.setFontSize(12);
    doc.setTextColor(40);
    doc.text(`Transfer Details`, 10, y);
    y += 10;

  
    autoTable(doc, {
      startY: y,
      head: [['Field', 'Value']],
      body: [
        ['Recipient User', transfer.recipientUser],
        ['Recipient CBU', transfer.recipientCbu.toString()],
        ['Origin User', transfer.originUser],
        ['Transfer Date', transferDateString],
        ['Transfer Amount', `$${transfer.transferAmount.toFixed(2)}`]
      ],
      theme: 'striped',
      headStyles: {
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontSize: 12
      },
      bodyStyles: {
        fillColor: [241, 248, 255],
        textColor: [0, 0, 0],
        fontSize: 10
      },
      alternateRowStyles: {
        fillColor: [255, 255, 255]
      },
      styles: {
        overflow: 'linebreak',
        cellPadding: 5
      }
    });

    y = doc.internal.pageSize.height - 20;
    doc.setLineWidth(0.5);
    doc.line(10, y, 200, y);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Generated by Transfer App', 105, y + 10, { align: 'center' });

    doc.save(`transfer${transfer.transfer_id}-report.pdf`);
  }

}

